spring.datasource.url= jdbc:postgresql://localhost:5432/gawpshardware
spring.datasource.username=postgresuser
spring.datasource.password=Frederick00263

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto= update